### ISSUE TITLE
Cannot load message class

### ISSUE THREAD

**Issue by abhaysjuneja** [cagbal/ros_people_object_detection_tensorflow#23]
I'm doing rostopic echo /object_tracker/tracks
and i'm getting this error

ERROR: Cannot load message class for [cob_perception_msgs/DetectionArray]. Are your messages built?

what do I do about this?

TIA

**Comment by cagbal** [comment]
Hi,
You may forget to source the workspace from the terminal that you want to echo. Can you verify that you did it?

**Comment by cagbal** [comment]
This issue seems inactive. I will close it in 2 days.
