### ISSUE TITLE
Explanation for poor tracking performance

### ISSUE THREAD

**Issue by thjoshi** [cagbal/ros_people_object_detection_tensorflow#24]
I believe your tracking problems are due to passing in [x, y, w, h] instead of [xmin, ymin, xmax, ymax].  The commenting for sort.update is also wrong in the submodule you're using.  The rest of the sort submodule uses [xmin, ymin, xmax, ymax].

https://github.com/cagbal/ros_people_object_detection_tensorflow/blob/f417985abe93a5a320ffa0846e9a484e0d45d5e6/src/tracker.py#L119

**Comment by cagbal** [comment]
Hmm.. I missed it. Thanks! I will check it soon.

**Comment by cagbal** [comment]
I think you are right.  
In this line: [x, y, xmax, ymax] is formatted to [x, y, s, r].
https://github.com/cagbal/experimenting-with-sort/blob/4927cf613618e3eb5bace7ca60acc0c752de8633/sort.py#L55    

So, we should use the appropriate input. I will fixed it soon with comments.
