### ISSUE TITLE
nothing publish in /object_detection/detections

### ISSUE THREAD

**Issue by melikavhf** [cagbal/ros_people_object_detection_tensorflow#28]
![topic](https://user-images.githubusercontent.com/24391257/41308299-c2aabf80-6e90-11e8-8f81-c49ba35ce533.png)

what can I do?I need x y and z

**Comment by cagbal** [comment]
Please look at this line: https://github.com/cagbal/ros_people_object_detection_tensorflow/blob/bc8c09d5af23406225c4f7d0b0d77842faa4065d/src/cob_people_object_detection_tensorflow/utils.py#L94

Actually program sets the detection_msg.mask field. It is not possible to see whole message from your image. Can you publish the image of your terminal when it is set to full screen?

**Comment by melikavhf** [comment]
Thanks for reply . 
it is not possible to get x and y from detected object(position of them) in this package?
![tooopi](https://user-images.githubusercontent.com/24391257/41333261-69432412-6ef6-11e8-8256-018421722df8.png)

**Comment by cagbal** [comment]
Unfortunately only the face positions.

13 Haz 2018 Çar 08:12 tarihinde Melika Vahidifar <notifications@github.com>
şunu yazdı:
