### ISSUE TITLE
Unable to display /object_detection/detections_image

### ISSUE THREAD

**Issue by kevinchoik** [cagbal/ros_people_object_detection_tensorflow#29]
When launching any of the .launch files, I'm unable to display the image using image_view with an error saying:

`ImageView.callback_image() could not convert image from '8UC3' to 'rgb8' ([8UC3] is not a color format. but [rgb8] is. The conversion does not make sense)`

The terminal output for the object tracker, on the other hand, seems to be working fine, since it responded to changes in the video input, which I could check with the raw footage.

I have all of the required projects installed, so I'm not sure where this is breaking. What should I do to resolve this problem?

**Comment by cagbal** [comment]
Could you try visualizing it by using RVIZ?

**Comment by kevinchoik** [comment]
That worked wonders.

Thank you!
