### ISSUE TITLE
road sign recognition application

### ISSUE THREAD

**Issue by yalan2017** [cagbal/ros_people_object_detection_tensorflow#32]
Hi dear
I am new in this area and have a simple question, I just found your code its interesting for me. I need use this code for road sign detection, I want to know is there any more tutorial or any paper for this code? 
Regards

**Comment by cagbal** [comment]
Hi, 

Please check this tutorial for custom object detection. 

https://www.youtube.com/playlist?list=PLQVvvaa0QuDcNK5GeCQnxYnSSaar2tpku

**Comment by cagbal** [comment]
I think I can close this issue, because it is more like question :+1:
