### ISSUE TITLE
Questions about projection 

### ISSUE THREAD

**Issue by jadhm** [cagbal/ros_people_object_detection_tensorflow#35]
Hi,

First of all I would like to thank you for this nice package. I have question about the projection. I would like to calculate the distance between the camera and the object so I adjusted the yaml file and put the input like this : face_topic: "/object_detection/detections" so I can get the distance from the object instead of the face (Do you think that is right what I did ?). It worked well but once I have more that one object the topic /face_recognizer/faces/realworld/position stops publishing the distance. I think because there are two or more distances at the same time, do you have any suggestions about what to change in order to get it work ? 
I have actually another question about the parameters of the camera. It might be a stupid question but I don't have a good experience with cameras but I am using realsense D435 how can I get those parameters : 
focal_length: 587.8 (this one depends on the camera so I think I can get it from the website of the camera)
cx of depth camera
cx: 351
cy for depth camera
cy: 227

Thank you in advance. 

Kind regards,
Jad

**Comment by cagbal** [comment]
Hey, 

I reproduced your error. The thing is I am using openni based driver so there is a depth_registration:=true parameter. If I set this parameter, the depth topic becomes active. So, you need to check the depth output of your camera topic and insert it into the depth_topic parameter inside of projection.yaml. 

I tried it and everything worked well. Hope this helps.

**Comment by jadhm** [comment]
Hi,
Thank you for you reply. I know that the calculations are so basic but it is basically just the distance between the camera and the mid point of the box right ? because this is what I am looking for. 
Can please provide me the name of the depth calculations package maybe I can I ask there about the parameters of the camera. 

For the error, I think I didn't explain well (my bad). I changed the depth topic to my camera's one and I got the x,y and z but once I see more that one object in a frame I get " nan" in the position.pose.x , .y and .z. please see the attached photos. It seems that there is conflict from the objects or maybe I am missing something  
![1](https://user-images.githubusercontent.com/25588361/44461308-94be7f00-a610-11e8-9328-f6609bd91526.png)
![2](https://user-images.githubusercontent.com/25588361/44461311-96884280-a610-11e8-96b1-ed4e4666f7a1.png)

**Comment by cagbal** [comment]
I figured out the issue. Thanks! I really missed that :+1: With a pull request, I will close this issue. 

It gives you the X and Y coordinates of the bounding box, and median depth of the points inside of this bounding box. 

The calibration would be this one: http://wiki.ros.org/openni_launch/Tutorials/IntrinsicCalibration

I'm not 100% sure though.
