### ISSUE TITLE
detecting faces from abrove

### ISSUE THREAD

**Issue by amalgmar12** [cagbal/ros_people_object_detection_tensorflow#38]
Hi,
I am sorry for redundant questions . I really need to continue my project urgently . I need you python code for face recognition  and extracting 3d locations of faces . I know you treat only rgb topic but what can I do to extract detection.pose.pose.x y z of cob_perception_msgs.msg an can I detect far faces from camera . Thank you for understanding .

**Comment by cagbal** [comment]
This package is already doing it. Please refer to README. You should provide an RGBD topic and it will publish a coarse XYZ position of faces.

**Comment by amalgmar12** [comment]
Ok ,can you please specify which module of this package should I change topics in order to extract 3d position and face encoding  at the same time .And my second question , what can I change in your code in order to detect faces from afar ?.Thank you for you time .It's so nice of you

**Comment by amalgmar12** [comment]
Hi,
Is there any news please ?

**Comment by cagbal** [comment]
Hi, 

Please go into this file:
https://github.com/cagbal/ros_people_object_detection_tensorflow/blob/master/launch/projection_params.yaml

And set your parameters, then you can get the depth values of faces. 

To get faces which are located far away, you can increase this scaling factor, it would effect up to some point, but not so much:

https://github.com/cagbal/ros_people_object_detection_tensorflow/blob/e301e3c33172e8a6e50f56e6439df9d285290710/src/face_recognizer.py#L82

Please also note that, this depth estimation is not so accurate, maybe you can go with some other advanced methods.

**Comment by cagbal** [comment]
Then, unfortunately, there is nothing much to do. Sorry for that. I will check the issue that you mention about projection py

**Comment by amalgmar12** [comment]
Did you check the issue ?

**Comment by cagbal** [comment]
No probably I will not have time to check it in one week.

**Comment by cagbal** [comment]
for now, I'll close it, because I could not encounter any problem.
