### ISSUE TITLE
Very High CPU Usage with Tracker

### ISSUE THREAD

**Issue by atyshka** [cagbal/ros_people_object_detection_tensorflow#48]
Thanks for this great project! I've been trying this out and one thing I noticed is very high CPU usage for the tracker. While you would think object detection and face recognition to be the most intensive tasks, they use far less CPU than the tracker. On my 9th gen i7 processor, running the tracker node puts 3 full CPU cores at 100% usage. This is much too high for a simple Kalman Filter tracker. Is anyone able to reproduce this issue?

**Comment by cagbal** [comment]
Hi, I am glad that it works for you. I'll look into the problem. But it may take a little bit of time.

**Comment by riddhimahajan10** [comment]
so what can be done in a case where the machine detects two different faces with same name??
i have done the training and there is atleast 300 pictures each for a person and training done till 30,000 steps. can u help me out with this type of case?

**Comment by atyshka** [comment]
@riddhimahajan10 that’s a valid issue but please don’t post on a completely different topic (this is about CPU usage for the tracker). If you have problems please file a new issue

**Comment by riddhimahajan10** [comment]
I'm sorry,
Since I'm a new user here I'm just learning.
So can u help me out in this case anyway.

**Comment by cagbal** [comment]
@riddhimahajan10 thanks for the interest.

- The names must be unique or you need to implement your logic. Contributions are welcome. 
- Regarding your second question, I am not so sure about your application. My face recog. node is using face_recognition package which does not need any training. Are you trying to train your object detector for different people?

**Comment by riddhimahajan10** [comment]
So if we want to detect only label of person for any person the camera
sees....what Coco API model should we use? Do you have any model in your
mind? That only shows label of a person.
